<template>
  <div>
    <div>dialog demo</div>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
  </div>
</template>
